-- ****************** SqlDBM: MySQL ******************;
-- ***************************************************;
SET foreign_key_checks = 0;
/*DROP TABLE `CO_SO_VAT_CHAT-GIAY_TO_MINH_CHUNG`;


DROP TABLE `NHAN_VIEN_BOI_BAN - BUNG_BE_ITEM`;


DROP TABLE `KHACH_MANG_DI`;


DROP TABLE `NGUYEN_LIEU - ITEM`;


DROP TABLE `NHAN_VIEN_ORDER - CAP_NHAT_TINH_TRANG_ITEM`;


DROP TABLE `NHAN_VIEN_BEP - CHE BIEN ITEM`;


DROP TABLE `THU_NGAN_XUAT_HOA_DON_GOM_CAC_ITEM`;


DROP TABLE `SHIPPER - ITEM - HOA_DON: GIAO_HANG`;


DROP TABLE `NHAN_VIEN`;


DROP TABLE `KE_TOAN - XUAT_GIAY_TO_MINH_CHUNG`;


DROP TABLE `CO_SO_VAT_CHAT`;


DROP TABLE `NGUYEN_LIEU`;


DROP TABLE `NHAN_VIEN_QUAN_LI`;


DROP TABLE `NHAN_VIEN_ORDER`;


DROP TABLE `NHAN_VIEN_BOI_BAN`;


DROP TABLE `NHAN_VIEN_BEP`;


DROP TABLE `NHAN_VIEN_KE_TOAN`;


DROP TABLE `NHAN_VIEN_THU_NGAN`;


DROP TABLE `NHAN_VIEN_SHIPPER`;


DROP TABLE `KHACH_NGOI_BAN`;


DROP TABLE `ITEM - DON_DAT_HANG - MON`;


DROP TABLE `HOA_DON`;


DROP TABLE `DON_DAT_HANG-KHACH_CHINH_SUA`;


DROP TABLE `KHACH_DUOC_HUONG_KM`;


DROP TABLE `KHACH`;


DROP TABLE `ITEM`;


DROP TABLE `DON_DAT_HANG`;


DROP TABLE `MON`;


DROP TABLE `KHUYEN_MAI`;


DROP TABLE `GIAY_TO_MINH_CHUNG`;


*/
-- ************************************** `KHACH`

CREATE TABLE `KHACH`
(
 `MA_SO_KHACH_HANG` VARCHAR(45) NOT NULL ,
 `HO_TEN`           VARCHAR(45) NOT NULL ,
 `NGAY_SINH`        DATE NOT NULL ,
 `GIOI_TINH`        VARCHAR(45) NOT NULL ,
 `DIA_CHI`          VARCHAR(45) NOT NULL ,
 `SDT`              NUMERIC NOT NULL ,
 `VIP`              BINARY NOT NULL ,

PRIMARY KEY (`MA_SO_KHACH_HANG`)
);

insert into `KHACH` (`MA_SO_KHACH_HANG`,`HO_TEN`,`NGAY_SINH`,`GIOI_TINH`,`DIA_CHI`,`SDT`,`VIP`) values
('001','Trần Văn Tiến','23-09-1995','Nam','quận Thủ Đức',01206662896,'0'),
('002','Nguyễn Lê Hồng','02-09-1997','Nữ','quận Tân Bình',01296178534,'0'),
('003','Trần Minh Giám','03-06-1897','Nam','quận 10',01208790989,'1'),
('004','Nguyễn Thị Minh Cúc','17-09-1994','Nữ','quận 1',01203961023,'0'),
('005','Lê Thị Thu Huyền','14-04-1988','Nữ','quận 5',01203862894,'1'),
('006','Huỳnh Thao','03-06-1988','Nam','quận Bình Thạnh',01208351945,'0'),
('007','Kha Văn Tân','09-08-1987','Nam','quận 3',01207643988,'0'),
('008','Lê Hòa','11-11-1995','Nữ','quận 11',01209899797,'1'),
('009','Lê Thị Thảo','16-04-1998','Nữ','quận 9',01202453876,'1'),
('010','Đỗ Lan','21-09-1995','Nữ','quận 7',01298674368,'0');



-- ************************************** `ITEM`

CREATE TABLE `ITEM`
(
 `MA_ITEM`    VARCHAR(45) NOT NULL ,
 `KICH_CO`    VARCHAR(45) NOT NULL ,
 `GIA_CU_THE` NUMERIC NOT NULL ,
 `GHI_CHU`    VARCHAR(45) DEFAULT NULL ,

PRIMARY KEY (`MA_ITEM`)
);
insert into `ITEM` (`MA_ITEM`,`KICH_CO`,`GIA_CU_THE`,`GHI_CHU`) VALUES
('001','S',150,''),
('002','M',209,''),
('003','S',230,''),
('004','L',120,''),
('005','L',320,''),
('006','S',20,''),
('007','S',30,''),
('008','M',130,''),
('009','M',32,''),
('010','L',50,'');




-- ************************************** `DON_DAT_HANG`

CREATE TABLE `DON_DAT_HANG`
(
 `MA_DON_HANG`  VARCHAR(45) NOT NULL ,
 `TEN_MON`      VARCHAR(45) NOT NULL ,
 `SO_LUONG`     NUMERIC NOT NULL ,
 `DON_GIA`      NUMERIC NOT NULL ,
 `THANH_TIEN`   NUMERIC NOT NULL ,
 `NGAY_GIO_DAT` DATETIME NOT NULL ,
 `TINH_TRANG`   VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_DON_HANG`)
);




-- ************************************** `MON`

CREATE TABLE `MON`
(
 `MA_MON`             VARCHAR(45) NOT NULL ,
 `TEN_MON`            VARCHAR(45) NOT NULL ,
 `GIA_THAM_KHAO`      NUMERIC NOT NULL ,
 `LOAI_MON`           VARCHAR(45) NOT NULL ,
 `THOI_GIAN_CHE_BIEN` DATETIME NOT NULL ,

PRIMARY KEY (`MA_MON`)
);

insert into `MON` (`MA_MON`,`TEN_MON`,`GIA_THAM_KHAO`,`LOAI_MON`,`THOI_GIAN_CHE_BIEN`) VALUES
('001','Bún bò Huế',60,'Món nước','20'),
('002','Phở gà',55,'Món nước','15'),
('003','Bánh cuốn nóng',70,'Các loại bánh','20'),
('004','Bánh thập cẩm',80,' Các loại bánh','25'),
('005','Gỏi măng',50,'Gỏi','15'),
('006','Gỏi vả',55,'Gỏi','15'),
('007','Nước dừa',35,'Nước uống','10'),
('008','Nước sâm',30,'Nước uống','5'),
('009','Chè long nhãn',45,'Tráng miệng','15'),
('010','Chè đậu ván',35,'Tráng miệng','10');



-- ************************************** `KHUYEN_MAI`

CREATE TABLE `KHUYEN_MAI`
(
 `MA_KM`              VARCHAR(45) NOT NULL ,
 `TEN_KM`             VARCHAR(45) NOT NULL ,
 `THOI_GIAN_BAT_DAU`  DATE NOT NULL ,
 `THOI_GIAN_KET_THUC` DATE NOT NULL ,
 `NOI_DUNG`           VARCHAR(45) NOT NULL ,
 `LOAI_HINH_KM`       VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_KM`)
);



insert into `KHUYEN_MAI`(`MA_KM`,`TEN_KM`,`THOI_GIAN_BAT_DAU`,`THOI_GIAN_KET_THUC`,`NOI_DUNG`,`LOAI_HINH_KM`) VALUES
('001','Mừng ngày 30/4 và 1/5','29-4-2018','2-5-2018','Giảm 10% hóa đơn','Chỉ dành cho khách VIP'),
('002','Mừng ngày cá tháng tư','31-03-2018','1-4-2018','Giảm 5% hóa đơn','Dành cho toàn bộ khách ăn tại chỗ'),
('003','Chào mừng tết Mậu Tuất','1-1-2018','5-1-2018','Giảm 10% hóa đơn','Chỉ dành cho khách VIP'),
('004','Chào mừng sinh nhật của nhà hàng','28-06-2017','28-06-2017','Giảm 15% hóa đơn','Dành chỗ toàn bộ khách hàng');

-- ************************************** `GIAY_TO_MINH_CHUNG`

CREATE TABLE `GIAY_TO_MINH_CHUNG`
(
 `MA_SO_GIAY_TO`  VARCHAR(45) NOT NULL ,
 `TEN_GIAY_TO`    VARCHAR(45) NOT NULL ,
 `LOAI_GIAY_TO`   VARCHAR(45) NOT NULL ,
 `THOI_GIAN_XUAT` DATE NOT NULL ,
 `SO_TIEN`        NUMERIC NOT NULL ,

PRIMARY KEY (`MA_SO_GIAY_TO`)
);





-- ************************************** `KHACH_NGOI_BAN`

CREATE TABLE `KHACH_NGOI_BAN`
(
 `MA_SO_KHACH_HANG` VARCHAR(45) NOT NULL ,
 `SO_BAN`           NUMERIC NOT NULL ,

PRIMARY KEY (`MA_SO_KHACH_HANG`),
KEY `fkIdx_265` (`MA_SO_KHACH_HANG`),
CONSTRAINT `FK_265` FOREIGN KEY `fkIdx_265` (`MA_SO_KHACH_HANG`) REFERENCES `KHACH` (`MA_SO_KHACH_HANG`)
);

insert into `KHACH_NGOI_BAN`(`MA_SO_KHACH_HANG`,`SO_BAN`) VALUES
('001',03),
('007',07),
('009',08),
('006',01),
('003',02);



-- ************************************** `ITEM - DON_DAT_HANG - MON`

CREATE TABLE `ITEM - DON_DAT_HANG - MON`
(
 `MA_ITEM`     VARCHAR(45) NOT NULL ,
 `MA_DON_HANG` VARCHAR(45) NOT NULL ,
 `MA_MON`      VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_ITEM`, `MA_DON_HANG`),
KEY `fkIdx_315` (`MA_MON`),
CONSTRAINT `FK_315` FOREIGN KEY `fkIdx_315` (`MA_MON`) REFERENCES `MON` (`MA_MON`),
KEY `fkIdx_319` (`MA_ITEM`),
CONSTRAINT `FK_319` FOREIGN KEY `fkIdx_319` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`),
KEY `fkIdx_324` (`MA_DON_HANG`),
CONSTRAINT `FK_324` FOREIGN KEY `fkIdx_324` (`MA_DON_HANG`) REFERENCES `DON_DAT_HANG` (`MA_DON_HANG`)
);





-- ************************************** `HOA_DON`

CREATE TABLE `HOA_DON`
(
 `MA_HOA_DON`            VARCHAR(45) NOT NULL ,
 `TEN_MON`               VARCHAR(45) NOT NULL ,
 `DON_GIA`               NUMERIC NOT NULL ,
 `TONG_TIEN`             NUMERIC NOT NULL ,
 `NGAY_XUAT`             DATE NOT NULL ,
 `TINH_TRANG_THANH_TOAN` VARCHAR(45) NOT NULL ,
 `MA_SO_GIAY_TO`         VARCHAR(45) NOT NULL ,
 `MA_SO_KHACH_HANG`      VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_HOA_DON`),
KEY `fkIdx_355` (`MA_SO_GIAY_TO`),
CONSTRAINT `FK_355` FOREIGN KEY `fkIdx_355` (`MA_SO_GIAY_TO`) REFERENCES `GIAY_TO_MINH_CHUNG` (`MA_SO_GIAY_TO`),
KEY `fkIdx_359` (`MA_SO_KHACH_HANG`),
CONSTRAINT `FK_359` FOREIGN KEY `fkIdx_359` (`MA_SO_KHACH_HANG`) REFERENCES `KHACH` (`MA_SO_KHACH_HANG`)
);
/*INSERT INTO `HOA_DON`(`MA_HOA_DON`,`TEN_MON`,`DON_GIA`,`TONG_TIEN`,`NGAY_XUAT`,`TINH_TRANG_THANH_TOAN`,`MA_SO_GIAY_TO`,`MA_SO_KHACH_HANG`) VALUES
('001','Bùn bò Huế',)*/




-- ************************************** `DON_DAT_HANG-KHACH_CHINH_SUA`

CREATE TABLE `DON_DAT_HANG-KHACH_CHINH_SUA`
(
 `MA_DON_HANG`      VARCHAR(45) NOT NULL ,
 `MA_SO_KHACH_HANG` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_DON_HANG`, `MA_SO_KHACH_HANG`),
KEY `fkIdx_332` (`MA_DON_HANG`),
CONSTRAINT `FK_332` FOREIGN KEY `fkIdx_332` (`MA_DON_HANG`) REFERENCES `DON_DAT_HANG` (`MA_DON_HANG`),
KEY `fkIdx_336` (`MA_SO_KHACH_HANG`),
CONSTRAINT `FK_336` FOREIGN KEY `fkIdx_336` (`MA_SO_KHACH_HANG`) REFERENCES `KHACH` (`MA_SO_KHACH_HANG`)
);





-- ************************************** `KHACH_DUOC_HUONG_KM`

CREATE TABLE `KHACH_DUOC_HUONG_KM`
(
 `MA_KM`            VARCHAR(45) NOT NULL ,
 `MA_SO_KHACH_HANG` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_KM`, `MA_SO_KHACH_HANG`),
KEY `fkIdx_305` (`MA_KM`),
CONSTRAINT `FK_305` FOREIGN KEY `fkIdx_305` (`MA_KM`) REFERENCES `KHUYEN_MAI` (`MA_KM`),
KEY `fkIdx_310` (`MA_SO_KHACH_HANG`),
CONSTRAINT `FK_310` FOREIGN KEY `fkIdx_310` (`MA_SO_KHACH_HANG`) REFERENCES `KHACH` (`MA_SO_KHACH_HANG`)
);









-- ************************************** `NHAN_VIEN`

CREATE TABLE `NHAN_VIEN`
(
 `MA_SO_NHAN_VIEN`         VARCHAR(45) NOT NULL ,
 `HO_TEN`                  VARCHAR(45) NOT NULL ,
 `CMND`                    NUMERIC NOT NULL ,
 `NGAY_SINH`               DATE NOT NULL ,
 `GIOI_TINH`               VARCHAR(45) NOT NULL ,
 `DIA_CHI`                 VARCHAR(45) NOT NULL ,
 `SDT`                     NUMERIC NOT NULL ,
 `NGAY_BAT_DAU_LAM`        DATE NOT NULL ,
 `LUONG`                   NUMERIC NOT NULL ,
 `MA_SO_NHAN_VIEN_KE_TOAN` VARCHAR(45) NOT NULL ,
 `MA_SO_NHAN_VIEN_QUAN_LI` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_367` (`MA_SO_NHAN_VIEN_KE_TOAN`),
CONSTRAINT `FK_367` FOREIGN KEY `fkIdx_367` (`MA_SO_NHAN_VIEN_KE_TOAN`) REFERENCES `NHAN_VIEN_KE_TOAN` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_371` (`MA_SO_NHAN_VIEN_QUAN_LI`),
CONSTRAINT `FK_371` FOREIGN KEY `fkIdx_371` (`MA_SO_NHAN_VIEN_QUAN_LI`) REFERENCES `NHAN_VIEN_QUAN_LI` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `KE_TOAN - XUAT_GIAY_TO_MINH_CHUNG`

CREATE TABLE `KE_TOAN - XUAT_GIAY_TO_MINH_CHUNG`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `MA_SO_GIAY_TO`   VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`, `MA_SO_GIAY_TO`),
KEY `fkIdx_340` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_340` FOREIGN KEY `fkIdx_340` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN_KE_TOAN` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_345` (`MA_SO_GIAY_TO`),
CONSTRAINT `FK_345` FOREIGN KEY `fkIdx_345` (`MA_SO_GIAY_TO`) REFERENCES `GIAY_TO_MINH_CHUNG` (`MA_SO_GIAY_TO`)
);





-- ************************************** `CO_SO_VAT_CHAT`

CREATE TABLE `CO_SO_VAT_CHAT`
(
 `MA_SO_CSVC`              VARCHAR(45) NOT NULL ,
 `TEN`                     VARCHAR(45) NOT NULL ,
 `SO_LUONG`                NUMERIC NOT NULL ,
 `NGAY_MUA`                DATE NOT NULL ,
 `TINH_TRANG`              VARCHAR(45) NOT NULL ,
 `GIA`                     NUMERIC NOT NULL ,
 `MA_SO_NHAN_VIEN_QUAN_LI` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_CSVC`),
KEY `fkIdx_409` (`MA_SO_NHAN_VIEN_QUAN_LI`),
CONSTRAINT `FK_409` FOREIGN KEY `fkIdx_409` (`MA_SO_NHAN_VIEN_QUAN_LI`) REFERENCES `NHAN_VIEN_QUAN_LI` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `CO_SO_VAT_CHAT-GIAY_TO_MINH_CHUNG`

CREATE TABLE `CO_SO_VAT_CHAT-GIAY_TO_MINH_CHUNG`
(
 `MA_SO_CSVC`    VARCHAR(45) NOT NULL ,
 `MA_SO_GIAY_TO` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_CSVC`, `MA_SO_GIAY_TO`),
KEY `fkIdx_53` (`MA_SO_CSVC`),
CONSTRAINT `FK_53` FOREIGN KEY `fkIdx_53` (`MA_SO_CSVC`) REFERENCES `CO_SO_VAT_CHAT` (`MA_SO_CSVC`),
KEY `fkIdx_57` (`MA_SO_GIAY_TO`),
CONSTRAINT `FK_57` FOREIGN KEY `fkIdx_57` (`MA_SO_GIAY_TO`) REFERENCES `GIAY_TO_MINH_CHUNG` (`MA_SO_GIAY_TO`)
);


-- ************************************** `NHAN_VIEN_QUAN_LI`

CREATE TABLE `NHAN_VIEN_QUAN_LI`
(
 `MA_SO_NHAN_VIEN`    VARCHAR(45) NOT NULL ,
 `BANG_CAP`           VARCHAR(45) NOT NULL ,
 `SO_NAM_KINH_NGHIEM` NUMERIC NOT NULL ,
 `LY_LICH_TU_PHAP`    VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_228` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_228` FOREIGN KEY `fkIdx_228` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);




-- ************************************** `NHAN_VIEN_ORDER`

CREATE TABLE `NHAN_VIEN_ORDER`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `CAN_NANG`        NUMERIC NOT NULL ,
 `CHIEU_CAO`       NUMERIC NOT NULL ,
 `NGOAI_NGU`       VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_211` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_211` FOREIGN KEY `fkIdx_211` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);


-- ************************************** `NHAN_VIEN_BOI_BAN`

CREATE TABLE `NHAN_VIEN_BOI_BAN`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `CAN_NANG`        NUMERIC NOT NULL ,
 `CHIEU_CAO`       NUMERIC NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_201` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_201` FOREIGN KEY `fkIdx_201` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `NHAN_VIEN_BEP`

CREATE TABLE `NHAN_VIEN_BEP`
(
 `MA_SO_NHAN_VIEN`    VARCHAR(45) NOT NULL ,
 `SO_NAM_KINH_NGHIEM` NUMERIC NOT NULL ,
 `CHUC_VU_BEP`        VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_184` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_184` FOREIGN KEY `fkIdx_184` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `NHAN_VIEN_KE_TOAN`

CREATE TABLE `NHAN_VIEN_KE_TOAN`
(
 `MA_SO_NHAN_VIEN`    VARCHAR(45) NOT NULL ,
 `SO_NAM_KINH_NGHIEM` NUMERIC NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_175` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_175` FOREIGN KEY `fkIdx_175` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `NHAN_VIEN_THU_NGAN`

CREATE TABLE `NHAN_VIEN_THU_NGAN`
(
 `MA_SO_NHAN_VIEN`    VARCHAR(45) NOT NULL ,
 `SO_NAM_KINH_NGHIEM` NUMERIC NOT NULL ,
 `BANG_CAP`           VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_156` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_156` FOREIGN KEY `fkIdx_156` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `NHAN_VIEN_SHIPPER`

CREATE TABLE `NHAN_VIEN_SHIPPER`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `BIEN_KIEM_SOAT`  VARCHAR(45) NOT NULL ,
 `PHUONG_TIEN`     VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_117` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_117` FOREIGN KEY `fkIdx_117` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `NHAN_VIEN_BOI_BAN - BUNG_BE_ITEM`

CREATE TABLE `NHAN_VIEN_BOI_BAN - BUNG_BE_ITEM`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `MA_ITEM`         VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`, `MA_ITEM`),
KEY `fkIdx_397` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_397` FOREIGN KEY `fkIdx_397` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN_BOI_BAN` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_401` (`MA_ITEM`),
CONSTRAINT `FK_401` FOREIGN KEY `fkIdx_401` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`)
);





-- ************************************** `KHACH_MANG_DI`

CREATE TABLE `KHACH_MANG_DI`
(
 `MA_SO_KHACH_HANG`    VARCHAR(45) NOT NULL ,
 `MA_SO_NHAN_VIEN_BEP` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_KHACH_HANG`),
KEY `fkIdx_272` (`MA_SO_KHACH_HANG`),
CONSTRAINT `FK_272` FOREIGN KEY `fkIdx_272` (`MA_SO_KHACH_HANG`) REFERENCES `KHACH` (`MA_SO_KHACH_HANG`),
KEY `fkIdx_383` (`MA_SO_NHAN_VIEN_BEP`),
CONSTRAINT `FK_383` FOREIGN KEY `fkIdx_383` (`MA_SO_NHAN_VIEN_BEP`) REFERENCES `NHAN_VIEN_BEP` (`MA_SO_NHAN_VIEN`)
);





-- ************************************** `NGUYEN_LIEU - ITEM`

CREATE TABLE `NGUYEN_LIEU - ITEM`
(
 `MA_ITEM`        VARCHAR(45) NOT NULL ,
 `MA_NGUYEN_LIEU` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_ITEM`, `MA_NGUYEN_LIEU`),
KEY `fkIdx_413` (`MA_ITEM`),
CONSTRAINT `FK_413` FOREIGN KEY `fkIdx_413` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`),
KEY `fkIdx_418` (`MA_NGUYEN_LIEU`),
CONSTRAINT `FK_418` FOREIGN KEY `fkIdx_418` (`MA_NGUYEN_LIEU`) REFERENCES `NGUYEN_LIEU` (`MA_NGUYEN_LIEU`)
);





-- ************************************** `NHAN_VIEN_ORDER - CAP_NHAT_TINH_TRANG_ITEM`

CREATE TABLE `NHAN_VIEN_ORDER - CAP_NHAT_TINH_TRANG_ITEM`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `MA_ITEM`         VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`, `MA_ITEM`),
KEY `fkIdx_218` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_218` FOREIGN KEY `fkIdx_218` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN_ORDER` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_405` (`MA_ITEM`),
CONSTRAINT `FK_405` FOREIGN KEY `fkIdx_405` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`)
);





-- ************************************** `NHAN_VIEN_BEP - CHE BIEN ITEM`

CREATE TABLE `NHAN_VIEN_BEP - CHE BIEN ITEM`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `MA_ITEM`         VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`, `MA_ITEM`),
KEY `fkIdx_191` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_191` FOREIGN KEY `fkIdx_191` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN_BEP` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_387` (`MA_ITEM`),
CONSTRAINT `FK_387` FOREIGN KEY `fkIdx_387` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`)
);





-- ************************************** `THU_NGAN_XUAT_HOA_DON_GOM_CAC_ITEM`

CREATE TABLE `THU_NGAN_XUAT_HOA_DON_GOM_CAC_ITEM`
(
 `MA_HOA_DON`      VARCHAR(45) NOT NULL ,
 `MA_ITEM`         VARCHAR(45) NOT NULL ,
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_HOA_DON`, `MA_ITEM`),
KEY `fkIdx_163` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_163` FOREIGN KEY `fkIdx_163` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN_THU_NGAN` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_167` (`MA_HOA_DON`),
CONSTRAINT `FK_167` FOREIGN KEY `fkIdx_167` (`MA_HOA_DON`) REFERENCES `HOA_DON` (`MA_HOA_DON`),
KEY `fkIdx_379` (`MA_ITEM`),
CONSTRAINT `FK_379` FOREIGN KEY `fkIdx_379` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`)
);





-- ************************************** `SHIPPER - ITEM - HOA_DON: GIAO_HANG`

CREATE TABLE `SHIPPER - ITEM - HOA_DON: GIAO_HANG`
(
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,
 `MA_ITEM`         VARCHAR(45) NOT NULL ,
 `MA_HOA_DON`      VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_SO_NHAN_VIEN`, `MA_ITEM`),
KEY `fkIdx_144` (`MA_HOA_DON`),
CONSTRAINT `FK_144` FOREIGN KEY `fkIdx_144` (`MA_HOA_DON`) REFERENCES `HOA_DON` (`MA_HOA_DON`),
KEY `fkIdx_148` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_148` FOREIGN KEY `fkIdx_148` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN_SHIPPER` (`MA_SO_NHAN_VIEN`),
KEY `fkIdx_375` (`MA_ITEM`),
CONSTRAINT `FK_375` FOREIGN KEY `fkIdx_375` (`MA_ITEM`) REFERENCES `ITEM` (`MA_ITEM`)
);






-- ************************************** `NGUYEN_LIEU`

CREATE TABLE `NGUYEN_LIEU`
(
 `MA_NGUYEN_LIEU`  VARCHAR(45) NOT NULL ,
 `TEN_NGUYEN_LIEU` VARCHAR(45) NOT NULL ,
 `SO_LUONG`        NUMERIC NOT NULL ,
 `DON_VI_TINH`     VARCHAR(45) NOT NULL ,
 `TINH_TRANG`      VARCHAR(45) NOT NULL ,
 `MA_SO_GIAY_TO`   VARCHAR(45) NOT NULL ,
 `MA_SO_NHAN_VIEN` VARCHAR(45) NOT NULL ,

PRIMARY KEY (`MA_NGUYEN_LIEU`),
KEY `fkIdx_297` (`MA_SO_GIAY_TO`),
CONSTRAINT `FK_297` FOREIGN KEY `fkIdx_297` (`MA_SO_GIAY_TO`) REFERENCES `GIAY_TO_MINH_CHUNG` (`MA_SO_GIAY_TO`),
KEY `fkIdx_363` (`MA_SO_NHAN_VIEN`),
CONSTRAINT `FK_363` FOREIGN KEY `fkIdx_363` (`MA_SO_NHAN_VIEN`) REFERENCES `NHAN_VIEN` (`MA_SO_NHAN_VIEN`)
);


INSERT INTO `NGUYEN_LIEU`(`MA_NGUYEN_LIEU`,`TEN_NGUYEN_LIEU`,`SO_LUONG`,`DON_VI_TINH`,`TINH_TRANG`,`MA_SO_GIAY_TO`,`MA_SO_NHAN_VIEN`) VALUES
('001','Bún',15,'kg','còn','','001'),
('002','Phở',10,'kg','còn','','001'),
('003','Bột năng',5,'kg','còn','','001'),
('004','Tôm',5,'kg','còn','','002'),
('005','Thịt bò',4,'kg','còn','','002'),
('006','Thịt heo',4,'kg','còn','','002'),
('007','Măng',3,'kg','còn','','002'),
('008','Vả',2,'kg','còn','','002'),
('009','Dừa',20,'trái','còn','','003'),
('010','Sâm',20,'chai','hết','','003'),
('011','Nhãn',5,'kg','hết','','003'),
('012','Đậu ván',5,'kg','còn','','003');

